apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-06T22:11:42Z"
  generation: 1
  labels:
    app: kotlin-example-console
  name: kotlin-example-console
  namespace: default
  resourceVersion: "1760"
  uid: 6755e73f-125b-4426-b9b1-14027b41dd32
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kotlin-example-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kotlin-example-console
    spec:
      containers:
      - image: caprilespe/kotlin-example-console:v1
        imagePullPolicy: IfNotPresent
        name: kotlin-example-console
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-10-06T22:11:42Z"
    lastUpdateTime: "2023-10-06T22:11:42Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-10-06T22:11:42Z"
    lastUpdateTime: "2023-10-06T22:11:42Z"
    message: ReplicaSet "kotlin-example-console-86d9958656" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
